package com.etc.blog.dao;

import com.etc.blog.entity.Blog;
import java.util.List;

public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_blog
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_blog
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_blog
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    Blog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_blog
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    List<Blog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_blog
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    int updateByPrimaryKey(Blog record);
}