package com.etc.blog.dao;

import com.etc.blog.entity.Comment;
import java.util.List;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_comment
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_comment
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_comment
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    Comment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_comment
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    List<Comment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_comment
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    int updateByPrimaryKey(Comment record);
}