package com.etc.blog.dao;

import com.etc.blog.entity.Type;
import java.util.List;

public interface TypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_type
     *
     * @mbg.generated Mon Mar 14 15:44:41 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_type
     *
     * @mbg.generated Mon Mar 14 15:44:41 GMT+08:00 2022
     */
    int insert(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_type
     *
     * @mbg.generated Mon Mar 14 15:44:41 GMT+08:00 2022
     */
    Type selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_type
     *
     * @mbg.generated Mon Mar 14 15:44:41 GMT+08:00 2022
     */
    List<Type> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_type
     *
     * @mbg.generated Mon Mar 14 15:44:41 GMT+08:00 2022
     */
    int updateByPrimaryKey(Type record);
}