package com.etc.blog.dao;

import com.etc.blog.entity.User;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    int updateByPrimaryKey(User record);
}