package com.etc.blog.entity;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.id
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.appreciation
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Boolean appreciation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.commentabled
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Boolean commentabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.content
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.creatTime
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.first_picture
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private String firstPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.flag
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.published
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Boolean published;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.recommend
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Boolean recommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.share_statement
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private String shareStatement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.title
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.updatetime
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.views
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Integer views;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.type_id
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Long typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_blog.user_id
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.id
     *
     * @return the value of w_blog.id
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.id
     *
     * @param id the value for w_blog.id
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.appreciation
     *
     * @return the value of w_blog.appreciation
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Boolean getAppreciation() {
        return appreciation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.appreciation
     *
     * @param appreciation the value for w_blog.appreciation
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setAppreciation(Boolean appreciation) {
        this.appreciation = appreciation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.commentabled
     *
     * @return the value of w_blog.commentabled
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Boolean getCommentabled() {
        return commentabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.commentabled
     *
     * @param commentabled the value for w_blog.commentabled
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setCommentabled(Boolean commentabled) {
        this.commentabled = commentabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.content
     *
     * @return the value of w_blog.content
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.content
     *
     * @param content the value for w_blog.content
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.creatTime
     *
     * @return the value of w_blog.creatTime
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.creatTime
     *
     * @param creattime the value for w_blog.creatTime
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.first_picture
     *
     * @return the value of w_blog.first_picture
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public String getFirstPicture() {
        return firstPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.first_picture
     *
     * @param firstPicture the value for w_blog.first_picture
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setFirstPicture(String firstPicture) {
        this.firstPicture = firstPicture == null ? null : firstPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.flag
     *
     * @return the value of w_blog.flag
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.flag
     *
     * @param flag the value for w_blog.flag
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.published
     *
     * @return the value of w_blog.published
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Boolean getPublished() {
        return published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.published
     *
     * @param published the value for w_blog.published
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setPublished(Boolean published) {
        this.published = published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.recommend
     *
     * @return the value of w_blog.recommend
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Boolean getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.recommend
     *
     * @param recommend the value for w_blog.recommend
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setRecommend(Boolean recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.share_statement
     *
     * @return the value of w_blog.share_statement
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public String getShareStatement() {
        return shareStatement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.share_statement
     *
     * @param shareStatement the value for w_blog.share_statement
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setShareStatement(String shareStatement) {
        this.shareStatement = shareStatement == null ? null : shareStatement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.title
     *
     * @return the value of w_blog.title
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.title
     *
     * @param title the value for w_blog.title
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.updatetime
     *
     * @return the value of w_blog.updatetime
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.updatetime
     *
     * @param updatetime the value for w_blog.updatetime
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.views
     *
     * @return the value of w_blog.views
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.views
     *
     * @param views the value for w_blog.views
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.type_id
     *
     * @return the value of w_blog.type_id
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.type_id
     *
     * @param typeId the value for w_blog.type_id
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_blog.user_id
     *
     * @return the value of w_blog.user_id
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_blog.user_id
     *
     * @param userId the value for w_blog.user_id
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}