package com.etc.blog.entity;

public class Type {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_type.id
     *
     * @mbg.generated Mon Mar 14 15:44:41 GMT+08:00 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_type.name
     *
     * @mbg.generated Mon Mar 14 15:44:41 GMT+08:00 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_type.id
     *
     * @return the value of w_type.id
     *
     * @mbg.generated Mon Mar 14 15:44:41 GMT+08:00 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_type.id
     *
     * @param id the value for w_type.id
     *
     * @mbg.generated Mon Mar 14 15:44:41 GMT+08:00 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_type.name
     *
     * @return the value of w_type.name
     *
     * @mbg.generated Mon Mar 14 15:44:41 GMT+08:00 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_type.name
     *
     * @param name the value for w_type.name
     *
     * @mbg.generated Mon Mar 14 15:44:41 GMT+08:00 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}