package com.etc.blog.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.id
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.nickname
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.username
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.email
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.avatar
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.type
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.creattime
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.updatetime
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.id
     *
     * @return the value of w_user.id
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.id
     *
     * @param id the value for w_user.id
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.nickname
     *
     * @return the value of w_user.nickname
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.nickname
     *
     * @param nickname the value for w_user.nickname
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.username
     *
     * @return the value of w_user.username
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.username
     *
     * @param username the value for w_user.username
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.email
     *
     * @return the value of w_user.email
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.email
     *
     * @param email the value for w_user.email
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.avatar
     *
     * @return the value of w_user.avatar
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.avatar
     *
     * @param avatar the value for w_user.avatar
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.type
     *
     * @return the value of w_user.type
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.type
     *
     * @param type the value for w_user.type
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.creattime
     *
     * @return the value of w_user.creattime
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.creattime
     *
     * @param creattime the value for w_user.creattime
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.updatetime
     *
     * @return the value of w_user.updatetime
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.updatetime
     *
     * @param updatetime the value for w_user.updatetime
     *
     * @mbg.generated Thu Mar 10 17:07:28 GMT+08:00 2022
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}