package com.etc.forum.entity;

public class Announcement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_announcement.id
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_announcement.published
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private Boolean published;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_announcement.title
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_announcement.content
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_announcement.id
     *
     * @return the value of f_announcement.id
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_announcement.id
     *
     * @param id the value for f_announcement.id
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_announcement.published
     *
     * @return the value of f_announcement.published
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public Boolean getPublished() {
        return published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_announcement.published
     *
     * @param published the value for f_announcement.published
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setPublished(Boolean published) {
        this.published = published;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_announcement.title
     *
     * @return the value of f_announcement.title
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_announcement.title
     *
     * @param title the value for f_announcement.title
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_announcement.content
     *
     * @return the value of f_announcement.content
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_announcement.content
     *
     * @param content the value for f_announcement.content
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}