package com.etc.forum.entity;

import java.util.Date;

public class Trade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_trade.id
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_trade.payer
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    private Long payer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_trade.payee
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    private Long payee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_trade.money
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_trade.title
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_trade.creattime
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_trade.ordernumber
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    private String ordernumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_trade.id
     *
     * @return the value of f_trade.id
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_trade.id
     *
     * @param id the value for f_trade.id
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_trade.payer
     *
     * @return the value of f_trade.payer
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public Long getPayer() {
        return payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_trade.payer
     *
     * @param payer the value for f_trade.payer
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public void setPayer(Long payer) {
        this.payer = payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_trade.payee
     *
     * @return the value of f_trade.payee
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public Long getPayee() {
        return payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_trade.payee
     *
     * @param payee the value for f_trade.payee
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public void setPayee(Long payee) {
        this.payee = payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_trade.money
     *
     * @return the value of f_trade.money
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_trade.money
     *
     * @param money the value for f_trade.money
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_trade.title
     *
     * @return the value of f_trade.title
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_trade.title
     *
     * @param title the value for f_trade.title
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_trade.creattime
     *
     * @return the value of f_trade.creattime
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_trade.creattime
     *
     * @param creattime the value for f_trade.creattime
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_trade.ordernumber
     *
     * @return the value of f_trade.ordernumber
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_trade.ordernumber
     *
     * @param ordernumber the value for f_trade.ordernumber
     *
     * @mbg.generated Sun Apr 17 13:32:33 GMT+08:00 2022
     */
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber == null ? null : ordernumber.trim();
    }
}