package com.etc.forum.entity;

import java.util.Date;

public class UpFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_upfile.id
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_upfile.name
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_upfile.type
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_upfile.url
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_upfile.userid
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_upfile.creattime
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_upfile.money
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private Integer money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_upfile.id
     *
     * @return the value of f_upfile.id
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_upfile.id
     *
     * @param id the value for f_upfile.id
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_upfile.name
     *
     * @return the value of f_upfile.name
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_upfile.name
     *
     * @param name the value for f_upfile.name
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_upfile.type
     *
     * @return the value of f_upfile.type
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_upfile.type
     *
     * @param type the value for f_upfile.type
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_upfile.url
     *
     * @return the value of f_upfile.url
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_upfile.url
     *
     * @param url the value for f_upfile.url
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_upfile.userid
     *
     * @return the value of f_upfile.userid
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_upfile.userid
     *
     * @param userid the value for f_upfile.userid
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_upfile.creattime
     *
     * @return the value of f_upfile.creattime
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_upfile.creattime
     *
     * @param creattime the value for f_upfile.creattime
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_upfile.money
     *
     * @return the value of f_upfile.money
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_upfile.money
     *
     * @param money the value for f_upfile.money
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}