package com.etc.forum.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.id
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.name
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.email
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.money
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.headimg
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private String headimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.creattime
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.updatetime
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.id
     *
     * @return the value of f_user.id
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.id
     *
     * @param id the value for f_user.id
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.name
     *
     * @return the value of f_user.name
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.name
     *
     * @param name the value for f_user.name
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.email
     *
     * @return the value of f_user.email
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.email
     *
     * @param email the value for f_user.email
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.money
     *
     * @return the value of f_user.money
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.money
     *
     * @param money the value for f_user.money
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.headimg
     *
     * @return the value of f_user.headimg
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public String getHeadimg() {
        return headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.headimg
     *
     * @param headimg the value for f_user.headimg
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setHeadimg(String headimg) {
        this.headimg = headimg == null ? null : headimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.creattime
     *
     * @return the value of f_user.creattime
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.creattime
     *
     * @param creattime the value for f_user.creattime
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.updatetime
     *
     * @return the value of f_user.updatetime
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.updatetime
     *
     * @param updatetime the value for f_user.updatetime
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}