package com.etc.onlineordering.dao;

import com.etc.onlineordering.entity.Customer;
import java.util.List;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    Customer selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    List<Customer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    int updateByPrimaryKey(Customer record);
}