package com.etc.onlineordering.dao;

import com.etc.onlineordering.entity.DisheComment;
import java.util.List;

public interface DisheCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishecomment
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishecomment
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    int insert(DisheComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishecomment
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    DisheComment selectByPrimaryKey(Integer commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishecomment
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    List<DisheComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishecomment
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    int updateByPrimaryKey(DisheComment record);
}