package com.etc.onlineordering.dao;

import com.etc.onlineordering.entity.Shop;
import java.util.List;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer shopid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    Shop selectByPrimaryKey(Integer shopid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    List<Shop> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    int updateByPrimaryKey(Shop record);
}