package com.etc.onlineordering.dao;

import com.etc.onlineordering.entity.ShopCol;
import java.util.List;

public interface ShopColMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcol
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer collectionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcol
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    int insert(ShopCol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcol
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    ShopCol selectByPrimaryKey(Integer collectionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcol
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    List<ShopCol> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopcol
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    int updateByPrimaryKey(ShopCol record);
}