package com.etc.onlineordering.entity;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.province
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.district
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.detail
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.type
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.refid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer refid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.code
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.phone
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressid
     *
     * @return the value of address.addressid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressid
     *
     * @param addressid the value for address.addressid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.province
     *
     * @return the value of address.province
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.province
     *
     * @param province the value for address.province
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.district
     *
     * @return the value of address.district
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.district
     *
     * @param district the value for address.district
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.detail
     *
     * @return the value of address.detail
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.detail
     *
     * @param detail the value for address.detail
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.type
     *
     * @return the value of address.type
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.type
     *
     * @param type the value for address.type
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.refid
     *
     * @return the value of address.refid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getRefid() {
        return refid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.refid
     *
     * @param refid the value for address.refid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setRefid(Integer refid) {
        this.refid = refid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.code
     *
     * @return the value of address.code
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.code
     *
     * @param code the value for address.code
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.phone
     *
     * @return the value of address.phone
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.phone
     *
     * @param phone the value for address.phone
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}