package com.etc.onlineordering.entity;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.userid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.username
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.password
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.role
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.userid
     *
     * @return the value of customer.userid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.userid
     *
     * @param userid the value for customer.userid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.username
     *
     * @return the value of customer.username
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.username
     *
     * @param username the value for customer.username
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.password
     *
     * @return the value of customer.password
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.password
     *
     * @param password the value for customer.password
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.role
     *
     * @return the value of customer.role
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.role
     *
     * @param role the value for customer.role
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setRole(Integer role) {
        this.role = role;
    }
}