package com.etc.onlineordering.entity;

import java.util.Date;

public class DisheComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishecomment.commentid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer commentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishecomment.userid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishecomment.disheid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer disheid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishecomment.score
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishecomment.username
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishecomment.time
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishecomment.dishename
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String dishename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishecomment.content
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishecomment.commentid
     *
     * @return the value of dishecomment.commentid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishecomment.commentid
     *
     * @param commentid the value for dishecomment.commentid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishecomment.userid
     *
     * @return the value of dishecomment.userid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishecomment.userid
     *
     * @param userid the value for dishecomment.userid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishecomment.disheid
     *
     * @return the value of dishecomment.disheid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getDisheid() {
        return disheid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishecomment.disheid
     *
     * @param disheid the value for dishecomment.disheid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setDisheid(Integer disheid) {
        this.disheid = disheid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishecomment.score
     *
     * @return the value of dishecomment.score
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishecomment.score
     *
     * @param score the value for dishecomment.score
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishecomment.username
     *
     * @return the value of dishecomment.username
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishecomment.username
     *
     * @param username the value for dishecomment.username
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishecomment.time
     *
     * @return the value of dishecomment.time
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishecomment.time
     *
     * @param time the value for dishecomment.time
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishecomment.dishename
     *
     * @return the value of dishecomment.dishename
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getDishename() {
        return dishename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishecomment.dishename
     *
     * @param dishename the value for dishecomment.dishename
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setDishename(String dishename) {
        this.dishename = dishename == null ? null : dishename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishecomment.content
     *
     * @return the value of dishecomment.content
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishecomment.content
     *
     * @param content the value for dishecomment.content
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}