package com.etc.onlineordering.entity;

public class Dishe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishe.disheid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer disheid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishe.shopid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishe.name
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishe.image
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishe.price
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishe.stock
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishe.type
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishe.disheid
     *
     * @return the value of dishe.disheid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getDisheid() {
        return disheid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishe.disheid
     *
     * @param disheid the value for dishe.disheid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setDisheid(Integer disheid) {
        this.disheid = disheid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishe.shopid
     *
     * @return the value of dishe.shopid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishe.shopid
     *
     * @param shopid the value for dishe.shopid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishe.name
     *
     * @return the value of dishe.name
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishe.name
     *
     * @param name the value for dishe.name
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishe.image
     *
     * @return the value of dishe.image
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishe.image
     *
     * @param image the value for dishe.image
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishe.price
     *
     * @return the value of dishe.price
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishe.price
     *
     * @param price the value for dishe.price
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishe.stock
     *
     * @return the value of dishe.stock
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishe.stock
     *
     * @param stock the value for dishe.stock
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishe.type
     *
     * @return the value of dishe.type
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishe.type
     *
     * @param type the value for dishe.type
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}