package com.etc.onlineordering.entity;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shopid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.name
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.address
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.phone
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.time
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.score
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.image
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.headimg
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String headimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.type
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.count
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.aveprice
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Double aveprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.introduce
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private String introduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shopid
     *
     * @return the value of shop.shopid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shopid
     *
     * @param shopid the value for shop.shopid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.name
     *
     * @return the value of shop.name
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.name
     *
     * @param name the value for shop.name
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.address
     *
     * @return the value of shop.address
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.address
     *
     * @param address the value for shop.address
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.phone
     *
     * @return the value of shop.phone
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.phone
     *
     * @param phone the value for shop.phone
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.time
     *
     * @return the value of shop.time
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.time
     *
     * @param time the value for shop.time
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.score
     *
     * @return the value of shop.score
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.score
     *
     * @param score the value for shop.score
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.image
     *
     * @return the value of shop.image
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.image
     *
     * @param image the value for shop.image
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.headimg
     *
     * @return the value of shop.headimg
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getHeadimg() {
        return headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.headimg
     *
     * @param headimg the value for shop.headimg
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setHeadimg(String headimg) {
        this.headimg = headimg == null ? null : headimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.type
     *
     * @return the value of shop.type
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.type
     *
     * @param type the value for shop.type
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.count
     *
     * @return the value of shop.count
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.count
     *
     * @param count the value for shop.count
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.aveprice
     *
     * @return the value of shop.aveprice
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Double getAveprice() {
        return aveprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.aveprice
     *
     * @param aveprice the value for shop.aveprice
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setAveprice(Double aveprice) {
        this.aveprice = aveprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.introduce
     *
     * @return the value of shop.introduce
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.introduce
     *
     * @param introduce the value for shop.introduce
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }
}