package com.etc.onlineordering.entity;

public class ShopCol {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcol.collectionid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer collectionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcol.shopid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcol.userid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcol.collectionid
     *
     * @return the value of shopcol.collectionid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getCollectionid() {
        return collectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcol.collectionid
     *
     * @param collectionid the value for shopcol.collectionid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setCollectionid(Integer collectionid) {
        this.collectionid = collectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcol.shopid
     *
     * @return the value of shopcol.shopid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcol.shopid
     *
     * @param shopid the value for shopcol.shopid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcol.userid
     *
     * @return the value of shopcol.userid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcol.userid
     *
     * @param userid the value for shopcol.userid
     *
     * @mbg.generated Sun Nov 28 19:30:49 GMT+08:00 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}