package com.etc.forum.dao;

import com.etc.forum.entity.Announcement;
import java.util.List;

public interface AnnouncementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_announcement
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_announcement
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    int insert(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_announcement
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    Announcement selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_announcement
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    List<Announcement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_announcement
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    int updateByPrimaryKey(Announcement record);
}