package com.etc.forum.dao;

import com.etc.forum.entity.Comment;
import java.util.List;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_comment
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_comment
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_comment
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    Comment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_comment
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    List<Comment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_comment
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    int updateByPrimaryKey(Comment record);
}