package com.etc.forum.dao;

import com.etc.forum.entity.Login;
import java.util.List;

public interface LoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    int insert(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    Login selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    List<Login> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_login
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    int updateByPrimaryKey(Login record);
}