package com.etc.forum.dao;

import com.etc.forum.entity.Type;
import java.util.List;

public interface TypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_type
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_type
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    int insert(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_type
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    Type selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_type
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    List<Type> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_type
     *
     * @mbg.generated Fri Mar 25 11:38:56 GMT+08:00 2022
     */
    int updateByPrimaryKey(Type record);
}